'use client';
import {useEffect,useState} from 'react';
import ReactMarkdown from 'react-markdown';
import {ArrowLeft,ArrowDownToLine,Check,Copy,FileText,Layers3,ShieldCheck} from 'lucide-react';
import type {PublishedSkill} from '@/lib/skill-store';

type Tab='overview'|'files'|'versions';
export default function SkillDetailClient({slug}:{slug:string}){
  const [skill,setSkill]=useState<PublishedSkill|null>(null),[markdown,setMarkdown]=useState(''),[error,setError]=useState(''),[tab,setTab]=useState<Tab>('overview'),[copied,setCopied]=useState(false);
  useEffect(()=>{let alive=true;fetch(`/api/skills/${encodeURIComponent(slug)}`).then(async response=>{const data=await response.json() as {error?:string;skill:PublishedSkill;markdown:string};if(!response.ok)throw new Error(data.error||'加载失败');if(alive){setSkill(data.skill);setMarkdown(data.markdown);document.title=`${data.skill.title} · 庞伟深`;}}).catch(e=>{if(alive)setError(e.message)});return()=>{alive=false}},[slug]);
  const prompt=skill?`请阅读并安装这个 Skill：${location.origin}/api/skills/${skill.slug}/download 。先检查 SKILL.md 与附带文件，再按其说明使用。`:'';
  async function copy(){try{await navigator.clipboard.writeText(prompt);setCopied(true);setTimeout(()=>setCopied(false),2200)}catch{}}
  const visibleMarkdown=markdown.replace(/^---\s*\n[\s\S]*?\n---\s*\n/,'');
  return <div className="skill-page"><header className="skill-topbar"><a className="skill-brand" href="/#skills"><span className="skill-brand-symbol">PWS</span><span>庞伟深 <small>Skill Library</small></span></a><nav><a href="/#skills">实用 Skills</a><a href="/#super-tools">超级工具</a><a href="/experience">经验沉淀</a></nav><a className="skill-publish-link" href="/skills/upload">＋ 发布 Skill</a></header>
  <main className="skill-container"><a className="skill-back" href="/#skills"><ArrowLeft size={16}/> 返回 Skills</a>{error?<div className="skill-error"><h1>暂时无法打开这个 Skill</h1><p>{error}</p><a href="/#skills">返回资源库</a></div>:!skill?<div className="skill-loading">正在加载 Skill…</div>:<><section className="skill-intro"><span className="skill-icon"><Layers3 size={26}/></span><div><div className="skill-kicker">PWS SKILL COLLECTION</div><h1>{skill.title}</h1><p className="skill-handle">@pws/{skill.slug}</p><div className="skill-trust"><span><ShieldCheck size={15}/> 由作者发布</span><span>v{skill.versions[0].version}</span><span>更新于 {new Date(skill.updatedAt).toLocaleDateString('zh-CN')}</span></div></div></section><p className="skill-summary">{skill.summary}</p><div className="skill-tags"><span>{skill.category}</span>{skill.tags.map(tag=><span key={tag}>{tag}</span>)}</div><div className="skill-layout"><div className="skill-primary"><div className="skill-tabs" role="tablist" aria-label="Skill 内容">{([['overview','概述'],['files','文件'],['versions','版本历史']] as const).map(([id,label])=><button key={id} role="tab" aria-selected={tab===id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</div>{tab==='overview'&&<article className="skill-markdown"><ReactMarkdown>{visibleMarkdown}</ReactMarkdown></article>}{tab==='files'&&<div className="skill-file-list"><div><FileText size={19}/><span><strong>SKILL.md</strong><small>技能说明与使用方法</small></span><a href={`/api/skills/${skill.slug}/download?format=markdown`}>下载</a></div>{skill.versions[0].zipKey&&<div><Layers3 size={19}/><span><strong>{skill.slug}-{skill.versions[0].version}.zip</strong><small>完整 Skill 文件包</small></span><a href={`/api/skills/${skill.slug}/download`}>下载</a></div>}</div>}{tab==='versions'&&<div className="skill-version-list">{skill.versions.map((version,index)=><div key={version.version}><span className="skill-version-dot"/><div><strong>v{version.version}</strong>{index===0&&<em>当前版本</em>}<small>{new Date(version.publishedAt).toLocaleString('zh-CN')}</small></div><a href={`/api/skills/${skill.slug}/download?version=${encodeURIComponent(version.version)}`}>下载</a></div>)}</div>}</div><aside className="skill-aside"><div className="skill-aside-card"><span className="skill-aside-label">快速安装</span><h2>交给你的 AI Agent</h2><p>复制这段提示词，让 Agent 先读取 Skill 内容并确认文件，再安装使用。</p><div className="skill-prompt">{prompt}</div><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'已复制':'复制安装提示词'}</button><a className="skill-download" href={`/api/skills/${skill.slug}/download`}><ArrowDownToLine size={17}/> 下载 {skill.versions[0].zipKey?'ZIP 包':'SKILL.md'}</a></div><div className="skill-author"><span>作者</span><strong>{skill.author}</strong><small>内容由作者上传，使用前请检查文件与权限。</small></div></aside></div></>}</main></div>;
}
