'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,Search,Pause,Play,Code2,Layers,Check,Copy,Menu,X,MoveUpRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {flushSync} from 'react-dom';

const resources=[
 {id:'research',type:'Skill',tag:'研究分析',title:'把一个问题，研究透。',description:'从问题拆解到证据核查，让研究有据可循。',art:'research /',color:'lime',sub:'QUESTION → EVIDENCE → INSIGHT',body:'适合需要判断产品、行业或新机会的研究。先明确研究对象、时间范围和交付标准，再查找一手来源，交叉验证关键结论。',steps:['写下待验证的问题与判断标准','收集原始来源，标记发布日期','把事实、推断与未知项分开记录'],template:'研究问题：\n研究范围与时间：\n关键证据及来源：\n我的判断：\n仍需核实：\n下一步行动：'},
 {id:'visual',type:'Skill',tag:'视觉创作',title:'让视觉想法，更准确地落地。',description:'把风格、构图与约束，整理成清楚的创作指令。',art:'/create',color:'purple',sub:'IDEA INTO SOMETHING REAL',body:'适合制作视觉素材前整理需求。先把尺寸、用途和不可改变的要素写清楚，再描述风格与构图，每轮只修改最影响结果的部分。',steps:['确定使用位置、比例与交付格式','分开写必须保留和可以探索的元素','用明确的修改项迭代并验收'],template:'用途与尺寸：\n主体：\n构图：\n颜色与材质：\n必须保留：\n需要避免：\n验收标准：'},
 {id:'brief',type:'工具',tag:'需求整理',title:'把“我想要”，变成能执行。',description:'一个轻量需求清单，把目标与验收放在一起。',art:'idea → brief',color:'peach',sub:'MAKE THE NEXT STEP CLEAR',body:'开始一个项目之前，用这张清单对齐目标。重点是写出用户完成什么动作、得到什么结果，以及什么情况下可以视为完成。',steps:['说明给谁用、解决哪一个问题','列出第一版必须完成的三个动作','为每个动作写下可观察的验收结果'],template:'给谁使用：\n要解决的问题：\n第一版包含：\n暂时不做：\n验收方式：'},
 {id:'review',type:'笔记',tag:'项目复盘',title:'项目结束后，值得留下什么？',description:'把做过的事情，变成下一次可以复用的方法。',art:'RE:VIEW',color:'blue',sub:'MAKE EXPERIENCE COUNT',body:'复盘不仅记录结果，也保留做决定时掌握的信息。把当时的假设、最终结果和中途调整放在一起，才能发现真正可迁移的方法。',steps:['记录目标与实际结果之间的差异','找出一个有效判断与一个错误假设','把可复用步骤整理成模板'],template:'原始目标：\n实际结果：\n关键决策：\n有效的方法：\n需要改变的假设：\n可复用资产：'},
 {id:'workflow',type:'Skill',tag:'工作流程',title:'让重复工作，有自己的流程。',description:'从一次完成，到每次都能稳定交付。',art:'01 → 02 → 03',color:'lime',sub:'LESS REPEAT. MORE CREATE.',body:'将重复工作拆成输入、处理、检查、输出四部分。先让流程可以手动复现，再考虑自动化，保留关键节点的人工判断。',steps:['找出每次都重复的步骤','为输入和输出设定固定格式','标注必须人工核查的节点'],template:'流程名称：\n触发条件：\n必要输入：\n执行步骤：\n检查节点：\n最终产出：'},
 {id:'archive',type:'工具',tag:'资产整理',title:'收藏之后，还能找得到。',description:'给零散素材一个清晰的位置和再次使用的理由。',art:'[ keep it ]',color:'cream',sub:'COLLECT LESS. CONNECT MORE.',body:'按使用场景整理，而不是按文件类型堆放。每条资源保留一句推荐理由、适用条件和原始出处，定期移除已经失效的内容。',steps:['按下次会怎样使用来分类','补上来源、使用理由和更新时间','把资源关联到具体项目'],template:'资源名称：\n原始链接：\n使用场景：\n推荐理由：\n限制条件：\n最近验证：'}
];
const superTools=[
 {name:'Figma',mark:'Fi',category:'界面设计',description:'设计界面、搭建原型，把想法变成可以讨论的方案。',url:'https://www.figma.com/',domain:'figma.com',color:'purple'},
 {name:'Canva',mark:'Ca',category:'内容创作',description:'制作海报、演示文稿和社交媒体图片。',url:'https://www.canva.com/',domain:'canva.com',color:'blue'},
 {name:'Notion',mark:'N',category:'知识整理',description:'把笔记、文档和项目资料整理在一个工作空间。',url:'https://www.notion.com/',domain:'notion.com',color:'cream'},
 {name:'Squoosh',mark:'Sq',category:'图片处理',description:'调整图片格式与质量，对比压缩前后的效果。',url:'https://squoosh.app/',domain:'squoosh.app',color:'peach'},
 {name:'TinyPNG',mark:'Tp',category:'图片压缩',description:'压缩 PNG、JPEG 和 WebP 图片，减小素材体积。',url:'https://tinypng.com/',domain:'tinypng.com',color:'lime'},
 {name:'Excalidraw',mark:'Ex',category:'白板绘图',description:'用手绘风格的图形，快速画出思路与流程。',url:'https://excalidraw.com/',domain:'excalidraw.com',color:'purple'}
];
const notes=[['01','经验不是做过，而是能复用。','把实践写成方法，让下一次更轻松。','review'],['02','先把问题说明白，再开始。','目标、约束和验收，值得多花一点时间。','brief'],['03','给灵感一个可以落地的出口。','用小实验验证想法，用结果决定下一步。','visual']];
function Arrow({size=20}:{size?:number}){return <ArrowUpRight size={size} strokeWidth={1.6}/>}
export default function Home(){
 const [filter,setFilter]=useState('全部');const [query,setQuery]=useState('');const [selected,setSelected]=useState<(typeof resources)[number]|null>(null);const [copied,setCopied]=useState(false);const [paused,setPaused]=useState(false);const [menu,setMenu]=useState(false);const [step,setStep]=useState(0);const [toast,setToast]=useState('');const heroRef=useRef<HTMLDivElement>(null);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');setPaused(mq.matches);const update=()=>setPaused(mq.matches);mq.addEventListener('change',update);return()=>mq.removeEventListener('change',update)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2400);return()=>clearTimeout(t)},[toast]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_resources',description:'搜索本站入门模板并更新资源库筛选。不会复制内容或发送信息。',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['全部','Skill','工具','笔记']}},required:['query','category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const data=input as {query?:unknown;category?:unknown};if(!data||typeof data.query!=='string'||typeof data.category!=='string'||!['全部','Skill','工具','笔记'].includes(data.category))throw new Error('请提供文字 query 和有效 category');const q=data.query;const category=data.category;flushSync(()=>{setQuery(q);setFilter(category)});document.getElementById('library')?.scrollIntoView({behavior:'instant'});return resources.filter(r=>(category==='全部'||category===r.type)&&`${r.title}${r.tag}${r.description}`.toLowerCase().includes(q.toLowerCase())).map(r=>({id:r.id,title:r.title,category:r.type}));}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 const shown=resources.filter(r=>(filter==='全部'||r.type===filter)&&`${r.title}${r.tag}${r.description}`.toLowerCase().includes(query.toLowerCase()));
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(selected.template);setCopied(true);setToast('模板已复制，可以开始填写了。')}catch{setToast('复制未成功，请选中下方模板手动复制。')}}
 function open(id:string){setCopied(false);setSelected(resources.find(r=>r.id===id)??null)}
 function filterTo(value:string){setFilter(value);document.getElementById('library')?.scrollIntoView({behavior:paused?'instant':'smooth'})}
 return <div className={`site ${paused?'motion-off':''}`}>
 <header className="site-header"><a href="#top" className="brand" aria-label="庞伟深 首页"><span className="brand-mark">pws<span>®</span></span><span className="brand-name">庞伟深<span>PERSONAL SPACE</span></span></a><nav className={menu?'nav open':'nav'} aria-label="主导航">{[['首页','#top'],['资源库','#library'],['超级工具','#super-tools'],['实践笔记','#notes'],['关于我','#about']].map(([label,href])=><a key={href} href={href} onClick={()=>setMenu(false)}>{label}</a>)}</nav><div className="nav-end"><span className="availability"><i/>持续探索中</span><button className="icon-button" aria-label={paused?'开启动画':'暂停动画'} aria-pressed={paused} onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>}</button><button className="icon-button mobile-menu" aria-label="切换菜单" onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></header>
 <main id="top">
 <section className="hero wrap"><div className="hero-copy"><p className="eyebrow"><i/> A SPACE TO LEARN, MAKE & SHARE</p><h1>保持好奇，<br/>让实践<span className="accent">生长。</span><span className="title-star" aria-hidden="true">✳</span></h1><p className="intro">你好，我是庞伟深。<br/>在这里，把好用的工具、做过的探索，<br className="desktop-break"/>变成值得分享、反复使用的经验。</p><div className="hero-actions"><a className="button primary" href="#library">探索我的资源库 <Arrow/></a><a className="text-link" href="#super-tools">打开超级工具 <ArrowRight size={18}/></a></div><p className="hero-foot">独立思考 <span>／</span> 动手实践 <span>／</span> 持续沉淀</p></div>
 <div className="hero-art" ref={heroRef} onPointerMove={e=>{if(paused||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.setProperty('--rx',`${-(e.clientY-r.top-r.height/2)/45}deg`);e.currentTarget.style.setProperty('--ry',`${(e.clientX-r.left-r.width/2)/45}deg`)}} onPointerLeave={e=>{e.currentTarget.style.setProperty('--rx','0deg');e.currentTarget.style.setProperty('--ry','0deg')}}><div className="art-top"><span>PWS / PERSONAL UNIVERSE</span><span>VOL. 001 <Arrow size={16}/></span></div><div className="art-grid"/><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="monogram" aria-hidden="true">pws<span>✳</span></div><button className="floating-label label-skills" onClick={()=>filterTo('Skill')}><Code2 size={15}/> SKILLS <ArrowUpRight size={14}/></button><button className="floating-label label-tools" onClick={()=>filterTo('工具')}><Layers size={15}/> TOOLS</button><a href="#notes" className="floating-label label-notes">NOTES <ArrowUpRight size={14}/></a><div className="art-bottom"><span>GOOD THINGS<br/>GROW WITH PRACTICE.</span><span className="round-arrow"><ArrowUpRight size={25}/></span></div></div>
 </section>
 <div className="ticker" aria-hidden="true"><div>{[0,1,2].map(i=><span key={i}>STAY CURIOUS <b>✳</b> KEEP MAKING <b>✳</b> 把经验变成下一步 <b>✳</b> BUILD. LEARN. REPEAT. <b>✳</b> </span>)}</div></div>
 <section id="library" className="section wrap"><div className="section-head"><div><p className="eyebrow">01 / THE RESOURCE COLLECTION</p><h2>好用的，<span className="muted-heading">值得留下。</span><ArrowUpRight/></h2></div><p>从一个工具，到一套方法。<br/>给下一次实践，多一点准备。</p></div><div className="library-toolbar"><div className="filters" aria-label="资源分类">{['全部','Skill','工具','笔记'].map(f=><button key={f} className={filter===f?'active':''} aria-pressed={filter===f} onClick={()=>setFilter(f)}>{f==='Skill'?'Skills':f==='工具'?'实用工具':f==='笔记'?'经验笔记':f}<span>{f==='全部'?resources.length:resources.filter(r=>r.type===f).length}</span></button>)}</div><label className="search"><Search size={17}/><input aria-label="搜索资源" placeholder="搜索工具、方法、灵感…" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={15}/></button>}</label></div><div className="resource-grid">{shown.map(r=><button className="resource-card" key={r.id} onClick={()=>open(r.id)}><div className={`card-art ${r.color}`}><div><span>{r.sub}</span><Arrow/></div><strong>{r.art}</strong><span>PWS COLLECTION — 001</span></div><div className="card-info"><div className="tags"><span>{r.type}</span><span>{r.tag}</span></div><h3>{r.title}</h3><p>{r.description}</p><div className="card-meta"><span>入门模板 · 示例内容</span><span>打开看看 <ArrowUpRight size={14}/></span></div></div></button>)}</div>{shown.length===0&&<div className="empty"><Search size={28}/><h3>暂时没有匹配的资源</h3><p>试试“研究”“视觉”或切换分类。</p><button className="button" onClick={()=>{setQuery('');setFilter('全部')}}>重置筛选</button></div>}<p className="collection-note">首批内容为可使用的入门模板；个人项目、亲测记录与正式 Skill 包将在整理后补充。</p></section>
 <section id="super-tools" className="lab-section"><div className="wrap section"><div className="section-head"><div><p className="eyebrow">02 / SUPER TOOLS</p><h2>超级工具<span className="muted-heading">，随手就能用。</span></h2></div><span className="live-label"><i/> USEFUL TOOLS, ONE CLICK AWAY</span></div><div className="super-tools-grid">{superTools.map(tool=><a key={tool.name} className="super-tool" href={tool.url} target="_blank" rel="noopener noreferrer" aria-label={`${tool.name}，${tool.category}，在新标签页打开官网`}><div className="super-tool-top"><span className={`super-tool-icon ${tool.color}`} aria-hidden="true">{tool.mark}</span><span className="super-tool-type">{tool.category}</span></div><h3>{tool.name}</h3><p>{tool.description}</p><div className="super-tool-bottom"><span>{tool.domain}</span><span>打开工具 <ArrowUpRight size={16}/></span></div></a>)}</div><p className="tools-caption">点击卡片，在新标签页打开工具官网。</p><div className="workflow"><div><span className="eyebrow">A REPEATABLE WAY</span><h3>把一次探索，变成一套方法。</h3></div><div className="workflow-steps">{['提出问题','动手验证','留下资产'].map((s,i)=><button key={s} className={step===i?'active':''} onClick={()=>setStep(i)}><span>0{i+1}</span>{s}<ArrowRight size={17}/></button>)}</div><p className="workflow-detail" aria-live="polite">{['先写清楚要解决什么、为谁解决，以及怎样才算完成。','做一个可以试用的小版本，观察结果，验证最关键的假设。','把有效步骤整理成模板、Skill 或笔记，让下一次可以直接接着做。'][step]}</p></div></div></section>
 <section id="notes" className="section wrap notes-section"><div className="section-head"><div><p className="eyebrow">03 / NOTES TO MY FUTURE SELF</p><h2>留下经验，<span className="muted-heading">也留下思考。</span></h2></div><span className="small-label">实践笔记 / 示例选题</span></div><div className="note-list">{notes.map(([n,title,desc,id])=><button className="note-row" key={n} onClick={()=>open(id)}><span className="note-number">{n}</span><div><h3>{title}</h3><p>{desc}</p></div><span className="note-type">方法与思考</span><span className="note-arrow"><Arrow/></span></button>)}</div></section>
 <section id="about" className="wrap about"><div className="about-symbol" aria-hidden="true">p<span>✳</span></div><div className="about-copy"><p className="eyebrow">THE PERSON BEHIND THIS SPACE</p><h2>你好，我是庞伟深。</h2><p>这里是我的个人实践空间。<br/>整理工具，探索 Skills，把零散经验慢慢变成自己的资产。<br/>希望每一次好奇，都能留下点什么。</p><div className="about-tags"><span>保持好奇</span><span>动手实践</span><span>分享有用的东西</span></div></div><div className="now"><span><i/> 正在进行</span><p>搭建这个小空间<br/>整理第一批资源<br/>整理超级工具入口</p><a href="#library">一起看看 <Arrow/></a></div></section>
 </main><footer className="wrap"><a className="footer-logo" href="#top">pws<span>®</span></a><p>保持好奇，持续创造。<span>© {new Date().getFullYear()} 庞伟深 · 个人实践空间</span></p><a href="#top">回到顶部 <MoveUpRight size={17}/></a></footer>
 <Dialog open={!!selected} onOpenChange={v=>{if(!v)setSelected(null)}}><DialogContent className="resource-dialog sm:max-w-2xl">{selected&&<><div className={`detail-banner ${selected.color}`}><span>{selected.type} / {selected.tag}</span><strong>{selected.art}</strong></div><DialogTitle className="detail-title">{selected.title}</DialogTitle><DialogDescription className="detail-description">{selected.body}</DialogDescription><ol className="detail-steps">{selected.steps.map((s,i)=><li key={s}><span>0{i+1}</span>{s}</li>)}</ol><div className="template-heading"><h3>从这份模板开始</h3><button onClick={copy}>{copied?<Check size={16}/>:<Copy size={16}/>} {copied?'已复制':'复制模板'}</button></div><pre className="template-content">{selected.template}</pre><p className="collection-note">入门示例 · 可复制使用，不代表个人项目经历或已发布的 Skill 包。</p></>}</DialogContent></Dialog>
 {toast&&<div className="toast" role="status">{toast}</div>}
 </div>
}
