'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,Search,Check,Copy,Menu,X,Grid2X2,List,Bookmark,RotateCcw,BookOpen,ExternalLink,CheckCheck,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {catalog,resources,filterCatalog,type CatalogItem} from '@/lib/catalog';
const scenes=['全部','研究分析','设计创作','效率办公','知识管理','开发学习','图片处理'];
const noteItems=[{id:'review',title:'经验不是做过，而是能复用。',description:'把实践写成方法，让下一次更轻松。'},{id:'brief',title:'先把问题说明白，再开始。',description:'目标、约束和验收，值得多花一点时间。'},{id:'visual',title:'给灵感一个可以落地的出口。',description:'用小实验验证想法，用结果决定下一步。'}];
function Logo(){return <span className="logo-frame"><span className="logo-crop"><img src="/brand/pws-line-logo-blue.png" alt="PWS" width={1536} height={1024}/></span></span>}
function FilterSelect({value,items,label,onChange}:{value:string;items:string[];label:string;onChange:(value:string)=>void}){return <Select value={value} onValueChange={v=>onChange(v??'全部')}><SelectTrigger className="filter-select" aria-label={label}><SelectValue>{value==='全部'?label:value}</SelectValue></SelectTrigger><SelectContent align="start" alignItemWithTrigger={false} className="filter-popup">{items.map(v=><SelectItem value={v} key={v}>{v==='全部'?label:v}</SelectItem>)}</SelectContent></Select>}
export default function Home(){
 const [kind,setKind]=useState('全部'),[scene,setScene]=useState('全部'),[source,setSource]=useState('全部'),[query,setQuery]=useState(''),[sort,setSort]=useState('default'),[view,setView]=useState('list'),[favoriteOnly,setFavoriteOnly]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[searchOpen,setSearchOpen]=useState(true),[menu,setMenu]=useState(false),[selected,setSelected]=useState<(typeof resources)[number]|null>(null),[copied,setCopied]=useState(false),[toast,setToast]=useState(''),[detailTab,setDetailTab]=useState('overview');
 const searchRef=useRef<HTMLInputElement>(null);
 const filters={kind,scene,source,query,sort,favoriteOnly,favorites};const shown=filterCatalog(filters);
 const isTools=source==='官方工具',isSkills=kind==='Skill';
 const title=favoriteOnly?'我的收藏':isTools?'超级工具':isSkills?'实用 Skills':'全部资源';
 const activeFilters=query.trim()!==''||scene!=='全部'||source!=='全部'||kind!=='全部'||favoriteOnly;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('pws-favorites')??'[]');if(Array.isArray(saved))setFavorites(saved.filter((id:unknown)=>typeof id==='string'&&catalog.some(r=>r.id===id)));const mode=localStorage.getItem('pws-view');if(mode==='grid'||mode==='list')setView(mode)}catch{}const route=()=>{const hash=location.hash;if(hash==='#super-tools'){setKind('全部');setSource('官方工具');setScene('全部');setFavoriteOnly(false)}else if(hash==='#skills'){setKind('Skill');setSource('全部');setScene('全部');setFavoriteOnly(false)}else if(hash==='#library'||hash==='#top'){setKind('全部');setSource('全部');setScene('全部');setFavoriteOnly(false)}};route();window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route)},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(id)},[toast]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_resources',description:'搜索个人资源库，按 Skill、工具或笔记筛选并更新可见结果。不会复制、收藏或打开外部网站。',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['全部','Skill','工具','笔记']}},required:['query','category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const data=input as {query?:unknown;category?:unknown};if(!data||typeof data.query!=='string'||typeof data.category!=='string'||!['全部','Skill','工具','笔记'].includes(data.category))throw new Error('请提供文字 query 和有效 category');const q=data.query,c=data.category;flushSync(()=>{setQuery(q);setKind(c);setScene('全部');setSource('全部');setFavoriteOnly(false);setSort('default');setSearchOpen(true)});document.getElementById('library')?.scrollIntoView({behavior:'instant'});return filterCatalog({query:q,kind:c,scene:'全部',source:'全部',sort:'default',favoriteOnly:false,favorites:[]}).map(r=>({id:r.id,title:r.title,category:r.kind}));}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[]);
 function reset(){setKind('全部');setScene('全部');setSource('全部');setQuery('');setSort('default');setFavoriteOnly(false)}
 function navigate(target:'all'|'skills'|'tools'){reset();if(target==='skills')setKind('Skill');if(target==='tools')setSource('官方工具');setMenu(false);document.getElementById('library')?.scrollIntoView({behavior:'smooth'})}
 function favorite(id:string){const next=favorites.includes(id)?favorites.filter(v=>v!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem('pws-favorites',JSON.stringify(next));setToast(next.includes(id)?'已加入本机收藏':'已取消收藏')}catch{setToast('本次收藏已更新，浏览器未允许保存到本机')}}
 function showResource(id:string){setSelected(resources.find(r=>r.id===id)??null);setCopied(false);setDetailTab('overview')}
 function setMode(mode:string){setView(mode);try{localStorage.setItem('pws-view',mode)}catch{}}
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(selected.template);setCopied(true);setToast('模板已复制')}catch{setToast('请选中模板内容手动复制')}}
 function entryContent(r:CatalogItem){return <><span className={`entry-icon ${r.color}`}>{r.mark}</span><span className="entry-copy"><span className="entry-title">{r.title}<span className="category-badge">{r.scene}</span></span><span className="entry-description">{r.description}</span></span><span className="entry-end"><span>{r.url?'访问官网':'查看模板'}</span>{r.url?<ArrowUpRight size={17}/>:<ChevronRight size={17}/>}</span></>}
 return <div className="site" id="top"><a className="skip-link" href="#library">跳到资源库</a><header className="site-header"><div className="header-inner"><a href="#library" className="brand" onClick={()=>navigate('all')}><Logo/><span className="brand-name">庞伟深<span>个人资源库</span></span></a><nav aria-label="主导航" className={menu?'main-nav is-open':'main-nav'}><a href="#library" onClick={()=>navigate('all')} className={!isTools&&!isSkills?'active':''}>资源库</a><a href="#skills" onClick={()=>navigate('skills')} className={isSkills?'active':''}>Skills</a><a href="#super-tools" onClick={()=>navigate('tools')} className={isTools?'active':''}>超级工具<span className="nav-badge">9</span></a><a href="#notes" onClick={()=>setMenu(false)}>实践笔记</a><a href="#about" onClick={()=>setMenu(false)}>关于我</a></nav><div className="header-actions"><button className={`collection-button ${favoriteOnly?'is-active':''}`} onClick={()=>{setFavoriteOnly(!favoriteOnly);setKind('全部');setSource('全部');setScene('全部');setQuery('');document.getElementById('library')?.scrollIntoView({behavior:'smooth'})}}><Bookmark size={16}/>我的收藏<span>{favorites.length}</span></button><a href="#about" className="profile-button">认识一下 <ArrowUpRight size={15}/></a><button className="icon-button menu-button" aria-label="切换导航" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X size={20}/>:<Menu size={20}/>}</button></div></div></header>
 <main><section className="catalog-section page-width" id="library"><span id="skills" className="anchor"/><span id="super-tools" className="anchor"/><div className="catalog-heading"><div><div className="eyebrow"><span className="status-dot"/> PWS COLLECTION</div><div className="heading-line"><h1>{title}</h1><p>{favoriteOnly?'留住好用的，下次直接找到。':isTools?'常用工具与网站，一个入口直达。':'整理好用的工具与方法，让每一次实践有所积累。'}</p></div></div><div className="catalog-total"><strong>{favoriteOnly?favorites.length:isTools?9:isSkills?3:catalog.length}</strong><span>{favoriteOnly?'本机收藏':'收录资源'}</span></div></div>
 <div className="catalog-toolbar"><div className="sort-options" aria-label="排列顺序">{[['default','默认排序'],['tools','工具优先'],['name','名称排序']].map(([value,label])=><button key={value} onClick={()=>setSort(value)} className={sort===value?'active':''} aria-pressed={sort===value}>{label}</button>)}</div><div className="filter-controls"><FilterSelect value={kind} items={['全部','Skill','工具','笔记']} label="所有资源类型" onChange={setKind}/><FilterSelect value={scene} items={scenes} label="所有使用场景" onChange={setScene}/><FilterSelect value={source} items={['全部','入门模板','官方工具']} label="所有来源" onChange={setSource}/><div className="toolbar-divider"/><button className={`icon-button ${searchOpen?'selected':''}`} aria-label={searchOpen?'收起搜索':'展开搜索'} aria-expanded={searchOpen} onClick={()=>{setSearchOpen(!searchOpen);if(!searchOpen)requestAnimationFrame(()=>searchRef.current?.focus())}}><Search size={17}/></button><ToggleGroup className="view-toggle" aria-label="显示方式" value={[view]} onValueChange={values=>{if(values[0])setMode(String(values[0]))}}><ToggleGroupItem value="list" aria-label="列表视图"><List size={17}/></ToggleGroupItem><ToggleGroupItem value="grid" aria-label="卡片视图"><Grid2X2 size={16}/></ToggleGroupItem></ToggleGroup></div></div>
 {searchOpen&&<label className="catalog-search"><Search size={19}/><input ref={searchRef} placeholder="搜索名称、描述或关键词，例如：设计、图片、研究…" aria-label="搜索资源" value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={16}/></button>:<span className="search-hint">搜索全部内容</span>}</label>}
 <div className="results-caption"><p aria-live="polite">共 <strong>{shown.length}</strong> 个结果{query.trim()&&<> · “{query.trim()}”</>}</p>{activeFilters?<button className="reset-button" onClick={reset}><RotateCcw size={13}/>重置筛选</button>:<span>持续整理，按需取用 <span className="caption-dot">·</span> 保持好奇</span>}</div>
 {shown.length>0?<div className={`entries ${view==='grid'?'grid-view':'list-view'}`}>{shown.map(r=><article key={r.id} className="entry">{r.url?<a className="entry-main" href={r.url} target="_blank" rel="noopener noreferrer" aria-label={`${r.title}，在新标签页打开官网`}>{entryContent(r)}</a>:<button className="entry-main" onClick={()=>showResource(r.resourceId!)}>{entryContent(r)}</button>}<div className="entry-meta"><span className={`source-badge ${r.url?'external-source':''}`}>{r.url?<ExternalLink size={12}/>:<BookOpen size={12}/>} {r.source}</span><span className="entry-domain">{r.domain??(r.kind==='Skill'?'Skill 入门示例':'可复制模板')}</span><button className={`bookmark-button ${favorites.includes(r.id)?'saved':''}`} aria-label={`${favorites.includes(r.id)?'取消收藏':'收藏'} ${r.title}`} aria-pressed={favorites.includes(r.id)} onClick={()=>favorite(r.id)}><Bookmark size={17} fill={favorites.includes(r.id)?'currentColor':'none'}/></button></div></article>)}</div>:<div className="empty-state"><div><Search size={28}/></div><h2>{favoriteOnly&&favorites.length===0?'还没有收藏的资源':'没有找到匹配的资源'}</h2><p>{favoriteOnly&&favorites.length===0?'点击资源旁的书签，就能把它留在这里。':'换个关键词，或清除筛选条件再试试。'}</p><button onClick={reset}>查看全部资源 <ArrowRight size={16}/></button></div>}
 <div className="catalog-bottom"><span>{favoriteOnly?'收藏仅保存在当前浏览器。':'模板为入门示例；外部工具点击后进入官网。'}</span><span>已展示全部 {shown.length} 项 <CheckCheck size={14}/></span></div></section>
 <section className="notes-section page-width" id="notes"><div className="section-heading"><div><span className="eyebrow">NOTES & PRACTICE</span><h2>实践笔记</h2></div><span>让经验成为下一次的起点</span></div><div className="notes-grid">{noteItems.map((n,i)=><button className="note-card" key={n.id} onClick={()=>showResource(n.id)}><span className="note-top"><BookOpen size={18}/><span>0{i+1} / 方法与思考</span><ArrowUpRight size={18}/></span><h3>{n.title}</h3><p>{n.description}</p><span className="note-footer">示例选题 <ArrowRight size={14}/></span></button>)}</div></section>
 <section className="about-section page-width" id="about"><div className="about-heading"><span className="about-avatar">庞</span><div><span className="eyebrow">BEHIND THE COLLECTION</span><h2>你好，我是庞伟深。</h2></div></div><p>这是我的个人实践空间。整理工具，探索 Skills，<br/>把零散经验慢慢变成可以反复使用的资产。</p><div className="about-status"><span className="status-dot"/><span>持续探索中</span><small>整理资源 · 动手实践 · 分享经验</small></div></section></main>
 <footer className="site-footer"><div className="page-width footer-top"><div className="footer-brand"><a href="#library" onClick={()=>navigate('all')}><Logo/><strong>庞伟深的个人资源库</strong></a><p>保持好奇，让实践生长。</p></div><div className="footer-links"><span>快捷入口</span><a href="#skills" onClick={()=>navigate('skills')}>实用 Skills</a><a href="#super-tools" onClick={()=>navigate('tools')}>超级工具</a><a href="#notes">实践笔记</a></div><div className="footer-links"><span>关于这个空间</span><a href="#about">关于我</a><button onClick={()=>{reset();setFavoriteOnly(true);document.getElementById('library')?.scrollIntoView({behavior:'smooth'})}}>我的收藏</button><a href="#top">回到顶部 ↑</a></div></div><div className="page-width footer-bottom"><span>© {new Date().getFullYear()} 庞伟深 · 个人实践空间</span><span>工具内容及商标归原作者所有。</span></div></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="resource-dialog sm:max-w-2xl">{selected&&<><div className="detail-head"><span className={`entry-icon ${selected.color}`}>{catalog.find(r=>r.id===selected.id)?.mark}</span><div><span className="detail-label">{selected.type} / {selected.tag}</span><DialogTitle className="detail-title">{selected.title}</DialogTitle></div></div><DialogDescription className="detail-description">{selected.description}</DialogDescription><Tabs value={detailTab} onValueChange={v=>setDetailTab(String(v))}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="overview">使用说明</TabsTrigger><TabsTrigger value="template">复制模板</TabsTrigger></TabsList><TabsContent value="overview" className="detail-panel"><p>{selected.body}</p><h3>从这三步开始</h3><ol className="detail-steps">{selected.steps.map((s,i)=><li key={s}><span>{i+1}</span>{s}</li>)}</ol><button className="dark-button" onClick={()=>setDetailTab('template')}>查看可复制模板 <ArrowRight size={16}/></button></TabsContent><TabsContent value="template" className="detail-panel"><div className="template-heading"><h3>填写后开始使用</h3><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'已复制':'复制模板'}</button></div><pre className="template-content">{selected.template}</pre></TabsContent></Tabs><div className="detail-foot"><span>入门示例，不代表已发布的 Skill 包。</span><button className={favorites.includes(selected.id)?'saved':''} onClick={()=>favorite(selected.id)}><Bookmark size={15}/>{favorites.includes(selected.id)?'已收藏':'收藏'}</button></div></>}</DialogContent></Dialog>
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}</div>
}
