'use client';
import {BrandLogo} from '@/components/brand-logo';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {ArrowUpRight,ArrowRight,ArrowDownToLine,Search,Star,Check,Copy,Menu,X,Grid2X2,List,RotateCcw,BookOpen,ExternalLink,CheckCheck,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {ToggleGroup,ToggleGroupItem} from '@/components/ui/toggle-group';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {catalog,resources,superTools,productivityTools,filterCatalog,type CatalogItem} from '@/lib/catalog';
import {SiteHeader} from './site-header';
import {skillIcon} from '@/lib/skill-icons';
import type {PublishedSkill} from '@/lib/skill-store';
const scenes=['全部','研究分析','设计创作','效率办公','知识管理','开发学习','图片处理'];
const noteItems=['review','brief','visual'].map(id=>resources.find(resource=>resource.id===id)!).filter(Boolean);
type SkillGroup='all'|'company'|'recommended'|'design';
function skillMatchesGroup(skill:PublishedSkill,group:SkillGroup){
 if(group==='all')return true;
 const labels=[skill.category,...skill.tags];
 if(skill.category==='公司Skill')return group==='company';
 if(skill.category==='设计Skill')return group==='design';
 if(group==='company')return labels.some(label=>/公司|企业/.test(label));
 if(group==='recommended')return labels.some(label=>/推荐|精选/.test(label));
 return labels.some(label=>/设计|视觉|Figma|figma/i.test(label));
}

function FilterSelect({value,items,label,onChange}:{value:string;items:string[];label:string;onChange:(value:string)=>void}){return <Select value={value} onValueChange={v=>onChange(v??'全部')}><SelectTrigger className="filter-select" aria-label={label}><SelectValue>{value==='全部'?label:value}</SelectValue></SelectTrigger><SelectContent align="start" alignItemWithTrigger={false} className="filter-popup">{items.map(v=><SelectItem value={v} key={v}>{v==='全部'?label:v}</SelectItem>)}</SelectContent></Select>}
export default function SiteClient({experienceMode:initialExperienceMode=false,initialSkills=null}:{experienceMode?:boolean;initialSkills?:PublishedSkill[]|null}){
 const [experienceMode,setExperienceMode]=useState(initialExperienceMode);
 const [kind,setKind]=useState('全部'),[scene,setScene]=useState('全部'),[source,setSource]=useState('全部'),[query,setQuery]=useState(''),[sort,setSort]=useState('default'),[skillGroup,setSkillGroup]=useState<SkillGroup>('all'),[view,setView]=useState('list'),[favoriteOnly,setFavoriteOnly]=useState(false),[favorites,setFavorites]=useState<string[]>([]),[searchOpen,setSearchOpen]=useState(true),[menu,setMenu]=useState(false),[selected,setSelected]=useState<(typeof resources)[number]|null>(null),[copied,setCopied]=useState(false),[toast,setToast]=useState(''),[detailTab,setDetailTab]=useState('overview');
 const [toolUses,setToolUses]=useState<Record<string,number>>({});
 useEffect(()=>{const refresh=()=>fetch('/api/tools/usage',{cache:'no-store'}).then(r=>r.ok?r.json():null).then((data:any)=>{if(data?.counts)setToolUses(data.counts)}).catch(()=>{});refresh();window.addEventListener('focus',refresh);return()=>window.removeEventListener('focus',refresh)},[]);
 function recordToolUse(item:CatalogItem){if(item.source!=='个人工具')return;fetch('/api/tools/usage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:item.id,eventId:crypto.randomUUID()}),keepalive:true}).then(r=>r.ok?r.json():null).then((data:any)=>{if(typeof data?.count==='number')setToolUses(previous=>({...previous,[item.id]:data.count}))}).catch(()=>{});}
 const searchRef=useRef<HTMLInputElement>(null);
 const [publishedSkills,setPublishedSkills]=useState<PublishedSkill[]>(initialSkills||[]);
 useEffect(()=>{let controller:AbortController|undefined,last=initialSkills?Date.now():0;const refresh=()=>{if(controller||Date.now()-last<30_000)return;controller=new AbortController();fetch('/api/skills',{signal:controller.signal}).then(response=>response.ok?response.json():null).then((data:unknown)=>{const payload=data as {skills?:PublishedSkill[]}|null;if(Array.isArray(payload?.skills)){setPublishedSkills(payload.skills);last=Date.now()}}).catch(()=>{}).finally(()=>{controller=undefined})};const restore=(event:PageTransitionEvent)=>{if(event.persisted)refresh()};if(!initialSkills)refresh();window.addEventListener('pageshow',restore);window.addEventListener('focus',refresh);return()=>{controller?.abort();window.removeEventListener('pageshow',restore);window.removeEventListener('focus',refresh)}},[initialSkills]);
 useEffect(()=>{setSelected(null);setMenu(false);setDetailTab('overview')},[experienceMode]);
 useEffect(()=>{
 const syncRoute=()=>{const experience=location.pathname==='/experience';setExperienceMode(experience);setSelected(null);setMenu(false);document.title=experience?'经验沉淀 · PWS STUDIO':'PWS STUDIO · 设计资源库';};
 const click=(event:MouseEvent)=>{if(event.defaultPrevented||event.button!==0||event.metaKey||event.ctrlKey||event.shiftKey||event.altKey)return;const anchor=(event.target as Element).closest('a');if(!anchor||anchor.target==='_blank'||anchor.hasAttribute('download'))return;const url=new URL(anchor.href,location.href);if(url.origin!==location.origin||!['/','/experience'].includes(url.pathname))return;event.preventDefault();if(url.pathname+url.hash!==location.pathname+location.hash)history.pushState(null,'',url.pathname+url.hash);flushSync(()=>{syncRoute();window.dispatchEvent(new HashChangeEvent('hashchange'))});window.scrollTo({top:0,behavior:'instant'});};
 document.addEventListener('click',click);window.addEventListener('popstate',syncRoute);return()=>{document.removeEventListener('click',click);window.removeEventListener('popstate',syncRoute);};
 },[]);
 const filters={kind,scene,source,query,sort,favoriteOnly,favorites};const shown=filterCatalog(filters);
 const matchedSkills=publishedSkills.filter(skill=>(!favoriteOnly||favorites.includes(`skill-${skill.slug}`))&&(kind==='全部'||kind==='Skill')&&source==='全部'&&(scene==='全部'||scene===skill.category)&&skillMatchesGroup(skill,skillGroup)&&`${skill.title} ${skill.summary} ${skill.author} ${skill.category} ${skill.tags.join(' ')}`.toLowerCase().includes(query.trim().toLowerCase()));
 const displayEntries:({kind:'skill';skill:PublishedSkill}|{kind:'catalog';item:CatalogItem})[]=[];
 displayEntries.push(...matchedSkills.map(skill=>({kind:'skill' as const,skill})),...shown.map(item=>({kind:'catalog' as const,item})));
 if(sort==='default')displayEntries.sort((a,b)=>Number(b.kind==='skill'&&b.skill.category==='公司Skill')-Number(a.kind==='skill'&&a.skill.category==='公司Skill'));
 if(sort==='name')displayEntries.sort((a,b)=>(a.kind==='skill'?a.skill.title:a.item.title).localeCompare(b.kind==='skill'?b.skill.title:b.item.title,'zh-CN'));
 if(sort==='tools')displayEntries.sort((a,b)=>Number(b.kind==='catalog'&&!!b.item.url)-Number(a.kind==='catalog'&&!!a.item.url));
 if(sort==='downloads')displayEntries.sort((a,b)=>(b.kind==='skill'?b.skill.downloadCount??0:-1)-(a.kind==='skill'?a.skill.downloadCount??0:-1));
 const isTools=source==='官方工具',isProductivityTools=source==='个人工具',isSkills=kind==='Skill';
 const title=favoriteOnly?'我的收藏':isProductivityTools?'提效工具':isTools?'宝藏网站':isSkills?'实用 Skills':'全部资源';
 const activeFilters=query.trim()!==''||scene!=='全部'||source!=='全部'||kind!=='全部'||skillGroup!=='all'||favoriteOnly;
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('pws-favorites')??'[]');if(Array.isArray(saved))setFavorites(saved.filter((id:unknown)=>typeof id==='string'));const mode=localStorage.getItem('pws-view');if(mode==='grid'||mode==='list')setView(mode)}catch{}const route=()=>{const hash=location.hash;setSkillGroup('all');setSort('default');if(hash==='#notes'){location.replace('/experience');return;}if(hash==='#super-tools'){setKind('全部');setSource('官方工具');setScene('全部');setFavoriteOnly(false);setView('grid')}else if(hash==='#productivity-tools'){setKind('全部');setSource('个人工具');setScene('全部');setFavoriteOnly(false);setView('grid')}else if(hash==='#skills'){setKind('Skill');setSource('全部');setScene('全部');setFavoriteOnly(false)}else if(hash==='#library'){setKind('全部');setSource('全部');setScene('全部');setFavoriteOnly(false)}};route();if(new URLSearchParams(location.search).get('favorites')==='1')setFavoriteOnly(true);window.addEventListener('hashchange',route);return()=>window.removeEventListener('hashchange',route)},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),2500);return()=>clearTimeout(id)},[toast]);
 useEffect(()=>{if(experienceMode)return;const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'search_resources',description:'搜索个人资源库，按 Skill、工具或笔记筛选并更新可见结果。不会复制、收藏或打开外部网站。',inputSchema:{type:'object',properties:{query:{type:'string'},category:{type:'string',enum:['全部','Skill','工具','笔记']}},required:['query','category'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input:unknown){const data=input as {query?:unknown;category?:unknown};if(!data||typeof data.query!=='string'||typeof data.category!=='string'||!['全部','Skill','工具','笔记'].includes(data.category))throw new Error('请提供文字 query 和有效 category');const q=data.query,c=data.category;flushSync(()=>{setQuery(q);setKind(c);setScene('全部');setSource('全部');setFavoriteOnly(false);setSort('default');setSearchOpen(true)});document.getElementById('library')?.scrollIntoView({behavior:'instant'});return filterCatalog({query:q,kind:c,scene:'全部',source:'全部',sort:'default',favoriteOnly:false,favorites:[]}).map(r=>({id:r.id,title:r.title,category:r.kind}));}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort()},[experienceMode]);
 function reset(){if(isTools){setScene('全部');setQuery('');setSort('default');setFavoriteOnly(false);return;}setKind('全部');setScene('全部');setSource('全部');setQuery('');setSort('default');setSkillGroup('all');setFavoriteOnly(false)}
 function favorite(id:string){const next=favorites.includes(id)?favorites.filter(v=>v!==id):[...favorites,id];setFavorites(next);try{localStorage.setItem('pws-favorites',JSON.stringify(next));setToast(next.includes(id)?'已加入本机收藏':'已取消收藏')}catch{setToast('本次收藏已更新，浏览器未允许保存到本机')}}
 async function favoriteSkill(slug:string){
 const id=`skill-${slug}`,saved=!favorites.includes(id);
 try{
 let visitorId=localStorage.getItem('pws-visitor-id');
 if(!visitorId){visitorId=crypto.randomUUID();localStorage.setItem('pws-visitor-id',visitorId)}
 const response=await fetch(`/api/skills/${slug}/favorite`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visitorId,saved})});
 if(!response.ok)throw new Error();
 const data=await response.json() as {count:number};
 favorite(id);
 setPublishedSkills(items=>items.map(skill=>skill.slug===slug?{...skill,favoriteCount:data.count}:skill));
 }catch{setToast('收藏未保存，请重试')}
 }
 function showResource(id:string){setSelected(resources.find(r=>r.id===id)??null);setCopied(false);setDetailTab('overview')}
 function setMode(mode:string){setView(mode);try{localStorage.setItem('pws-view',mode)}catch{}}
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(selected.template);setCopied(true);setToast('模板已复制')}catch{setToast('请选中模板内容手动复制')}}
 function entryContent(r:CatalogItem){return <>{r.example&&<span className="tool-example"><img src={r.example} alt="房间背景案例：丛林老虎主题与房间界面预览" width={720} height={1336} loading="lazy" decoding="async"/><span className="tool-example-caption">案例预览 <ArrowUpRight size={14}/></span></span>}<span className={`entry-icon ${r.color}`}>{r.logo?<img src={r.logo} alt="" width={48} height={48}/>:r.mark}</span><span className="entry-copy"><span className="entry-title">{r.title}<span className="category-badge">{r.scene}</span>{r.version&&<span className="tool-version">v{r.version}</span>}</span><span className="entry-description">{r.description}</span></span><span className="entry-end"><span>{r.url?'访问官网':'查看模板'}</span>{r.url?<ArrowUpRight size={17}/>:<ChevronRight size={17}/>}</span></>}
 return <div className="site" id="top"><a className="skip-link" href={experienceMode?'#experience':'#library'}>跳到主要内容</a><SiteHeader isSkills={isSkills} isProductivityTools={isProductivityTools} isTools={isTools} experienceMode={experienceMode} favoriteOnly={favoriteOnly} favoritesCount={favorites.length} onFavorites={()=>{setFavoriteOnly(!favoriteOnly);setKind('全部');setSource('全部');setScene('全部');setQuery('');window.scrollTo({top:0,behavior:'instant'})}}/>
 <main>{!experienceMode&&<section className={`catalog-section page-width ${isProductivityTools?'compact-catalog':''}`} id="library"><span id="skills" className="anchor"/><span id="productivity-tools" className="anchor"/><span id="super-tools" className="anchor"/><div className="catalog-heading"><div><div className="eyebrow"><span className="status-dot"/> PWS STUDIO</div><div className="heading-line"><h1>{title}</h1><p>{favoriteOnly?'留住好用的，下次直接找到。':isProductivityTools?'自己制作的实用工具，让重复工作更轻松。':isTools?'值得收藏的网站，一个入口直达。':'整理好用的工具与方法，让每一次实践有所积累。'}</p></div></div><div className="catalog-total"><strong>{favoriteOnly?favorites.length:isProductivityTools?productivityTools.length:isTools?superTools.length:isSkills?publishedSkills.length:catalog.length+publishedSkills.length}</strong><span>{favoriteOnly?'本机收藏':'收录资源'}</span></div></div>
 <div className="catalog-toolbar"><div className="sort-options" aria-label={isTools?"网站分类":isSkills?"Skill 分类与排序":"排列顺序"}>{isTools?<>{['全部','设计','工具','资讯','Skill'].map(value=><button key={value} onClick={()=>setScene(value)} className={scene===value?'active':''} aria-pressed={scene===value}>{value==='全部'?'全部网站':value}<span className="website-category-count">{catalog.filter(item=>item.source==='官方工具'&&(value==='全部'||item.scene===value)).length}</span></button>)}</>:isSkills?<>{([['all','全部Skill'],['company','公司Skill'],['recommended','推荐Skill'],['design','设计Skill']] as const).map(([value,label])=><button key={value} onClick={()=>setSkillGroup(value)} className={skillGroup===value?'active':''} aria-pressed={skillGroup===value}>{label}</button>)}<button className={sort==='downloads'?'active':''} aria-pressed={sort==='downloads'} onClick={()=>setSort(sort==='downloads'?'default':'downloads')}>下载量排序</button></>:[['default','默认排序'],['tools','工具优先'],['name','名称排序']].map(([value,label])=><button key={value} onClick={()=>setSort(value)} className={sort===value?'active':''} aria-pressed={sort===value}>{label}</button>)}</div><div className="filter-controls">{!isTools&&<><FilterSelect value={kind} items={['全部','Skill','工具','笔记']} label="所有资源类型" onChange={setKind}/><FilterSelect value={scene} items={scenes} label="所有使用场景" onChange={setScene}/><FilterSelect value={source} items={['全部','入门模板','个人工具','官方工具']} label="所有来源" onChange={setSource}/></>}<div className="toolbar-divider"/><button className={`icon-button ${searchOpen?'selected':''}`} aria-label={searchOpen?'收起搜索':'展开搜索'} aria-expanded={searchOpen} onClick={()=>{setSearchOpen(!searchOpen);if(!searchOpen)requestAnimationFrame(()=>searchRef.current?.focus())}}><Search size={17}/></button>{!isSkills&&<ToggleGroup className="view-toggle" aria-label="显示方式" value={[view]} onValueChange={values=>{if(values[0])setMode(String(values[0]))}}><ToggleGroupItem value="list" aria-label="列表视图"><List size={17}/></ToggleGroupItem><ToggleGroupItem value="grid" aria-label="卡片视图"><Grid2X2 size={16}/></ToggleGroupItem></ToggleGroup>}</div></div>
 {searchOpen&&<label className="catalog-search"><Search size={19}/><input ref={searchRef} placeholder="搜索名称、描述或关键词，例如：设计、图片、研究…" aria-label="搜索资源" value={query} onChange={e=>setQuery(e.target.value)}/>{query?<button aria-label="清空搜索" onClick={()=>setQuery('')}><X size={16}/></button>:<span className="search-hint">搜索全部内容</span>}</label>}
 <div className="results-caption"><p aria-live="polite">共 <strong>{shown.length+matchedSkills.length}</strong> 个结果{query.trim()&&<> · “{query.trim()}”</>}</p>{activeFilters?<button className="reset-button" onClick={reset}><RotateCcw size={13}/>重置筛选</button>:<span>持续整理，按需取用 <span className="caption-dot">·</span> 保持好奇</span>}</div>
 {displayEntries.length>0?<div key={`${kind}-${source}-${scene}-${skillGroup}-${sort}`} className={`entries ${!isSkills&&view==='grid'?'grid-view':'list-view'} ${isProductivityTools?'tools-entries productivity-entries':isTools?'tools-entries':''}`}>
 {displayEntries.map((row,index)=>row.kind==='skill'?<article key={`skill-${row.skill.slug}`} className="entry skill-entry" >
   <a className="entry-main" href={`/skills/${row.skill.slug}`}><span className="entry-icon blue skill-entry-icon">{skillIcon(row.skill.slug)?<img src={skillIcon(row.skill.slug)!} alt="" width={45} height={45}/>:<span>Sk</span>}</span><span className="entry-copy"><span className="entry-title">{row.skill.title}<span className="category-badge">{row.skill.category}</span></span><span className="entry-description">{row.skill.summary}</span></span><span className="entry-end">查看 Skill <ChevronRight size={17}/></span></a>
   <div className="entry-meta skill-stat-meta"><span className="skill-entry-author">作者 · {row.skill.author}</span><div className="skill-stat-bottom">{row.skill.source&&<a className="github-source" href={row.skill.source.url} target="_blank" rel="noopener noreferrer" title={`GitHub 仓库星标，核验于 ${row.skill.source.checkedAt.slice(0,10)}`}>GitHub ★ {new Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:1}).format(row.skill.source.stars)}</a>}<button className={`skill-favorite-stat ${favorites.includes(`skill-${row.skill.slug}`)?'saved':''}`} aria-label={`${favorites.includes(`skill-${row.skill.slug}`)?'取消收藏':'收藏'} ${row.skill.title}`} title="收藏数量" aria-pressed={favorites.includes(`skill-${row.skill.slug}`)} onClick={()=>favoriteSkill(row.skill.slug)}><Star size={17} fill={favorites.includes(`skill-${row.skill.slug}`)?'currentColor':'none'}/><span>{row.skill.favoriteCount??'—'}</span></button><span className="skill-download-count" title="下载量" aria-label={`${row.skill.downloadCount??0} 次下载`}><ArrowDownToLine size={17}/><span>{row.skill.downloadCount??'—'}</span></span></div></div>
 </article>:<article key={row.item.id} className={`entry ${row.item.example?'has-example':''}`} >{row.item.url?<a className="entry-main" href={row.item.url} onClick={()=>recordToolUse(row.item)} onAuxClick={event=>{if(event.button===1)recordToolUse(row.item)}} target="_blank" rel="noopener noreferrer" aria-label={`${row.item.title}，在新标签页打开官网`}>{entryContent(row.item)}</a>:<button className="entry-main" onClick={()=>showResource(row.item.resourceId!)}>{entryContent(row.item)}</button>}<div className="entry-meta"><span className={`source-badge ${row.item.url?'external-source':''}`}>{row.item.url?<ExternalLink size={12}/>:<BookOpen size={12}/>} {row.item.author?`作者 · ${row.item.author}`:row.item.source}</span>{row.item.source==='个人工具'?<span className="tool-use-count" title="从本站打开工具的累计次数">{toolUses[row.item.id]??'—'} 次使用</span>:<span className="entry-domain">{row.item.domain??'可复制模板'}</span>}<button className={`bookmark-button ${favorites.includes(row.item.id)?'saved':''}`} aria-label={`${favorites.includes(row.item.id)?'取消收藏':'收藏'} ${row.item.title}`} aria-pressed={favorites.includes(row.item.id)} onClick={()=>favorite(row.item.id)}><Star size={17} fill={favorites.includes(row.item.id)?'currentColor':'none'}/></button></div></article>)}</div>:<div className="empty-state"><div><Search size={28}/></div><h2>{favoriteOnly&&favorites.length===0?'还没有收藏的资源':isSkills&&skillGroup!=='all'&&!query.trim()?'这个分类还没有 Skill':'没有找到匹配的资源'}</h2><p>{favoriteOnly&&favorites.length===0?'点击资源旁的星星，就能把它留在这里。':isSkills&&skillGroup!=='all'&&!query.trim()?'后续收录到这个分类的 Skill 会显示在这里。':'换个关键词，或清除筛选条件再试试。'}</p><button onClick={isSkills?()=>{setSkillGroup('all');setQuery('');setScene('全部');setSort('default')}:reset}>{isSkills?'查看全部 Skill':'查看全部资源'} <ArrowRight size={16}/></button></div>}
 <div className="catalog-bottom"><span>{favoriteOnly?'收藏仅保存在当前浏览器。':isSkills?'点击 Skill 查看内容、文件与下载方式。':isProductivityTools?'使用次数按从本站打开工具的次数统计。':'外部工具点击后进入官网。'}</span><span>已展示全部 {displayEntries.length} 项 <CheckCheck size={14}/></span></div></section>}
 {experienceMode&&<section className="notes-section experience-page page-width" id="experience"><div className="section-heading"><div><span className="eyebrow">EXPERIENCE & KNOWLEDGE</span><h1>经验沉淀</h1></div><span>让经验成为下一次的起点</span></div><p className="experience-intro">记录判断，整理方法，把每一次探索变成可以复用的经验。</p><div className="notes-grid">{noteItems.map((n,i)=><button className="note-card" key={n.id} onClick={()=>showResource(n.id)}><span className="note-top"><BookOpen size={18}/><span>0{i+1} / 方法与思考</span><ArrowUpRight size={18}/></span><h3>{n.title}</h3><p>{n.description}</p><span className="note-footer">阅读与使用模板 <ArrowRight size={14}/></span></button>)}</div><p className="experience-note">当前收录 3 篇入门示例，点击查看方法说明与可复制模板。</p></section>}
 </main>
 <footer className="site-footer"><div className="page-width footer-top"><div className="footer-brand"><a href="/#library"><BrandLogo/></a><p>保持好奇，让实践生长。</p></div><div className="footer-links"><span>快捷入口</span><a href="/#skills">实用 Skills</a><a href="/#productivity-tools">提效工具</a><a href="/#super-tools">宝藏网站</a><a href="/experience">经验沉淀</a></div><div className="footer-links"><span>其他入口</span><button onClick={()=>{if(experienceMode){location.assign('/#library');return;}reset();setFavoriteOnly(true);window.scrollTo({top:0,behavior:'instant'})}}>{experienceMode?'全部资源':'我的收藏'}</button><a href="#top">回到顶部 ↑</a></div></div><div className="page-width footer-bottom"><span>© {new Date().getFullYear()} PWS STUDIO · 设计与实践</span><span>工具内容及商标归原作者所有。</span></div></footer>
 <Dialog open={!!selected} onOpenChange={open=>{if(!open)setSelected(null)}}><DialogContent className="resource-dialog sm:max-w-2xl">{selected&&<><div className="detail-head"><span className={`entry-icon ${selected.color}`}>{catalog.find(r=>r.id===selected.id)?.mark}</span><div><span className="detail-label">{selected.type} / {selected.tag}</span><DialogTitle className="detail-title">{selected.title}</DialogTitle></div></div><DialogDescription className="detail-description">{selected.description}</DialogDescription><Tabs value={detailTab} onValueChange={v=>setDetailTab(String(v))}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="overview">使用说明</TabsTrigger><TabsTrigger value="template">复制模板</TabsTrigger></TabsList><TabsContent value="overview" className="detail-panel"><p>{selected.body}</p><h3>从这三步开始</h3><ol className="detail-steps">{selected.steps.map((s,i)=><li key={s}><span>{i+1}</span>{s}</li>)}</ol><button className="dark-button" onClick={()=>setDetailTab('template')}>查看可复制模板 <ArrowRight size={16}/></button></TabsContent><TabsContent value="template" className="detail-panel"><div className="template-heading"><h3>填写后开始使用</h3><button onClick={copy}>{copied?<Check size={15}/>:<Copy size={15}/>} {copied?'已复制':'复制模板'}</button></div><pre className="template-content">{selected.template}</pre></TabsContent></Tabs><div className="detail-foot"><span>入门示例，不代表已发布的 Skill 包。</span><button className={favorites.includes(selected.id)?'saved':''} onClick={()=>favorite(selected.id)}><Star size={15}/>{favorites.includes(selected.id)?'已收藏':'收藏'}</button></div></>}</DialogContent></Dialog>
 {toast&&<div className="toast" role="status"><Check size={16}/>{toast}</div>}</div>
}
