'use client';
import {useState,type FormEvent} from 'react';
import {ArrowLeft,ArrowUpRight,FileText,UploadCloud} from 'lucide-react';

export default function UploadClient(){
 const [key,setKey]=useState(''),[title,setTitle]=useState(''),[slug,setSlug]=useState(''),[summary,setSummary]=useState(''),[category,setCategory]=useState(''),[tags,setTags]=useState(''),[version,setVersion]=useState('1.0.0'),[markdown,setMarkdown]=useState<File|null>(null),[zip,setZip]=useState<File|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[created,setCreated]=useState('');
 function applyMetadata(text:string){const match=text.match(/^---\s*\n([\s\S]*?)\n---/);if(!match)return;const name=match[1].match(/^name:\s*['"]?(.+?)['"]?\s*$/m)?.[1];const description=match[1].match(/^description:\s*['"]?(.+?)['"]?\s*$/m)?.[1];if(name){setTitle(previous=>previous||name);setSlug(previous=>previous||name.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,''))}if(description)setSummary(previous=>previous||description)}
 async function chooseMarkdown(file:File|null){setMarkdown(file);if(file)applyMetadata(await file.text())}
 async function chooseZip(file:File|null){setZip(file);setMessage('');if(!file)return;try{if(file.size>10*1024*1024)throw new Error('ZIP 文件不能超过 10 MB');const JSZip=(await import('jszip')).default;const archive=await JSZip.loadAsync(file);const skillFile=Object.values(archive.files).filter(entry=>!entry.dir&&/(^|\/)SKILL\.md$/i.test(entry.name)).sort((a,b)=>a.name.length-b.name.length)[0];if(!skillFile&&!markdown)throw new Error('ZIP 中未找到 SKILL.md，请另外上传 SKILL.md');if(skillFile)applyMetadata(await skillFile.async('string'))}catch(error){setMessage(error instanceof Error?error.message:'ZIP 无法读取');setZip(null)}}
 async function submit(event:FormEvent){event.preventDefault();setMessage('');if(!markdown&&!zip)return setMessage('请选择 SKILL.md，或包含 SKILL.md 的 ZIP');setBusy(true);try{const data=new FormData();for(const [name,value] of Object.entries({title,slug,summary,category,tags,version}))data.set(name,value);if(markdown)data.set('markdown',markdown);if(zip)data.set('zip',zip);const response=await fetch('/api/skills',{method:'POST',headers:{Authorization:`Bearer ${key}`},body:data});const result=await response.json() as {error?:string;skill:{slug:string}};if(!response.ok)throw new Error(result.error||'发布失败');setCreated(result.skill.slug)}catch(e){setMessage(e instanceof Error?e.message:'发布失败，请稍后重试')}finally{setBusy(false)}}
 return <div className="skill-page"><header className="skill-topbar"><a className="skill-brand" href="/#skills"><span className="skill-brand-symbol">PWS</span><span>庞伟深 <small>Skill Library</small></span></a><a className="skill-publish-link" href="/#skills">返回资源库</a></header><main className="upload-container"><a className="skill-back" href="/#skills"><ArrowLeft size={16}/> 返回 Skills</a><div className="upload-heading"><span className="skill-kicker">PUBLISH A SKILL</span><h1>发布你的 Skill</h1><p>上传 SKILL.md 或完整 ZIP 文件包，发布后会出现在资源库中，并拥有独立详情页。</p></div>{created?<div className="upload-success"><UploadCloud size={34}/><h2>Skill 已发布</h2><p>内容已经保存，可以查看详情和下载文件。</p><a href={`/skills/${created}`}>查看 Skill <ArrowUpRight size={16}/></a></div>:<form className="upload-form" onSubmit={submit}><section><div className="upload-section-title"><span>01</span><div><h2>基本信息</h2><p>帮助访客快速判断这个 Skill 适合什么任务。</p></div></div><div className="upload-field-grid"><label>Skill 名称<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={80} placeholder="例如：产品研究助手"/></label><label>英文标识<input value={slug} onChange={e=>setSlug(e.target.value.toLowerCase().replace(/[^a-z0-9-]/g,''))} required pattern="[a-z0-9][a-z0-9-]{1,59}" placeholder="product-research"/><small>用于详情页地址，仅小写字母、数字和连字符</small></label><label className="full">一句话介绍<textarea value={summary} onChange={e=>setSummary(e.target.value)} required maxLength={500} rows={3} placeholder="这个 Skill 能帮你完成什么？"/></label><label>分类<input value={category} onChange={e=>setCategory(e.target.value)} required maxLength={40} placeholder="例如：研究分析"/></label><label>标签<input value={tags} onChange={e=>setTags(e.target.value)} placeholder="研究, 产品, 写作"/><small>用逗号分隔，最多 8 个</small></label><label>版本号<input value={version} onChange={e=>setVersion(e.target.value)} required pattern="\d+\.\d+\.\d+(-[a-z0-9.-]+)?" placeholder="1.0.0"/></label></div></section><section><div className="upload-section-title"><span>02</span><div><h2>Skill 文件</h2><p>上传 SKILL.md，或上传包含 SKILL.md 的 ZIP。ZIP 中其他文件可在详情页浏览。</p></div></div><div className="upload-files"><label className="upload-drop"><FileText size={25}/><strong>{markdown?.name||'选择 SKILL.md'}</strong><small>Markdown 文件，最多 150 KB</small><input type="file" accept=".md,text/markdown" onChange={e=>chooseMarkdown(e.target.files?.[0]||null)}/></label><label className="upload-drop"><UploadCloud size={25}/><strong>{zip?.name||'选择完整 ZIP'}</strong><small>文件包，最多 10 MB</small><input type="file" accept=".zip,application/zip" onChange={e=>chooseZip(e.target.files?.[0]||null)}/></label></div></section><section className="upload-submit"><div><label>发布密钥<input type="password" value={key} onChange={e=>setKey(e.target.value)} required autoComplete="off" placeholder="仅站点所有者持有"/></label><small>发布权限仅向持有密钥的站点所有者开放。密钥不会保存在浏览器中。</small>{message&&<p role="alert">{message}</p>}</div><button type="submit" disabled={busy}>{busy?'正在发布…':'发布 Skill'} <ArrowUpRight size={17}/></button></section></form>}</main></div>;
}
